### ISSUE TITLE
Cant delete so cant update to fix

### ISSUE THREAD

**Issue by schneidmaster** [schneidmaster/gitreports.com#107]
Hi there was a 404 issue where when you created a new report you would get a 404 how ever i noticed the issues have been closed and tried now to use git reports and still get a 404 however im also unable to delete the report to get it to use patch

so either the 404 issue isnt resolved
or a delete is needed so people can use the patch

**Comment by moe-bugs** [comment]
Hello, I think i'm running into the same issue. I keep getting 404's when trying to submit a bug report. It looks like the issue might be caused due to having so many duplicate users for some reason as seen here:

<img src="http://i.imgur.com/H1ikrv3.png" width="550"/>

I'm not sure the exact steps i did to have so many duplicate users. 

I think maybe a delete repository link would be good to have in general.

The git reports repository link is <https://gitreports.com/repositories/13890>

**Comment by NYPD** [comment]
It seems like if I change the form-action to moe-bugs rather than NYPD:

<img src="http://i.imgur.com/TAfsKaF.png" width="450" />

I still get a 404 when submitting, but the issue does make it to the actual repo. 

I'm still not sure exactly what is going on. If there is any chance you can delete the moe-sounds repo from gitreports that would be great.

I'll have to keep poking around to see what is causing this.

**Comment by schneidmaster** [comment]
Hi. Your repositories are re-synced whenever you log out & log back in (which is why there's no delete button -- though perhaps there should be a manual re-sync button). Can you try that and see if it fixes your repository URL?

**Comment by NYPD** [comment]
I logged out and log back in with my "issue reporter" account and my main account and that didn't seem to work. It seems every time I do that I re-add users to the git reports:

<img src="http://i.imgur.com/IGMOKdQ.png" width="600">

**Comment by MathijsBesten** [comment]
I got the same issue, but only with one repo. I hope it can be fixed.

**Comment by CheweyZ** [comment]
Any chance this is getting fixed soon as it prevents anyone from making new issue trackers?

**Comment by schneidmaster** [comment]
I think I've finally cleared up this issue. GitHub used to always return 1 stable access token for each user, but they changed it to return a new access token on each login, so duplicate users were getting created. I changed the auth code to key off of username instead of access token and ran a migration to clean up duplicate users. Let me know if this clears things up for y'all.

**Comment by NYPD** [comment]
Works for me! thanks m8

**Comment by CheweyZ** [comment]
Works for me to THANKS

**Comment by schneidmaster** [comment]
Thanks all. Closing this issue, feel free to open a new one if something else related comes up.
