### ISSUE TITLE
End-user UX and GitHub ToS?

### ISSUE THREAD

**Issue by wireddown** [schneidmaster/gitreports.com#63]
I have been trying to implement a way for my users who don't have GitHub accounts to report problems and suggest improvements, but so far have been unsuccessful.

I was happy to find your site and service, and I'm evaluating its fitness for my needs.

I have two questions:

1. What would my users' experience be? The tutorial and about pages speak to what my experience as your user would be like, but I don't have a clear idea of what my users would experience. The closest I've seen is your *dogfood* link ( https://gitreports.com/issue/schneidmaster/gitreports.com ). If I wanted that form on my site, so I can control the look and feel, it looks like I would need host my own instance. Do I understand that correctly?
1. How does this service dovetail with the GitHub Terms of Service? My largest obstacle for implementing anonymous feedback has been Article A, sections 4 and 7 (below). Have you been able to receive guidance or permission from GitHub to implement your service, or do you use another approach that circumvents the single-user requirements entirely?

> **GitHub [Terms of Service](https://help.github.com/articles/github-terms-of-service/)**
>
> *A.4*
>
> Your login may only be used by one person - a single login shared by multiple people is not permitted. You may create separate logins for as many people as your plan allows.
>
> *A.7*
>
> One person or legal entity may not maintain more than one free account.

**Comment by schneidmaster** [comment]
1. The dogfood link is exactly what your users would experience UX-wise. On Git Reports, you can customize the repository display name, prompt ("Please enter your bug report...") and followup text, but not the appearance (colors, form shape and size, etc.). If you want more fine-grained UX control, then yes, you would need to host your own instance and edit the CSS appropriately.

2. I have not interacted with GitHub regarding this question. Git Reports uses the login of the user who configures the repository to post issues. My reading of the ToS you quoted would not preclude this usage- a "single login shared by multiple people" seems to imply multiple people having access to the username and password of a login and using that on the GitHub site (rather than an API token of one user being used to integrate a 3rd-party service), and Git Reports does not maintain any free accounts (much less more than one). The alternate reading would essentially prevent any usage of the GitHub API- for example, if I configure Travis CI using my GitHub account, it is technically "sharing" my login to access my code and run tests. But I suppose if you're super concerned about that legal angle, it may be prudent to find a different option - it's a free and open-source side project, I don't offer any legal guarantees :smile:

**Comment by wireddown** [comment]
Great, thanks :-) I'll close this issue.
