### ISSUE TITLE
Additional options for user email so it's not displayed in a public repository

### ISSUE THREAD

**Issue by rewphus** [schneidmaster/gitreports.com#91]
I want to encourage users to leave their email when submitting an issue so that we can follow up with them, but I don't think they will be comfortable with the fact that their email will then be listed with the issue in a public repository.  I am not familiar enough with GitHub issues to know what other options would be, but it would be nice to have some.

**Comment by mafzst** [comment]
+1
In France it's illegal to expose publicly email address unless the user explicitly grants it's permissions.
I suggest to not publish email to issue but sending it by email only

**Comment by sebastianskejoe** [comment]
I do believe that this is a good change, but unfortunately it has left us with the problem that often we are not able to contact users because they forget to check the box. A lot of our users are not very tech-savvy so even if we encourage users to check the box.
A possible soulution could be to either make it an option to check the box by default or to include the title of the submitted issue and the email adress of the submitter in the notification email.

**Comment by mafzst** [comment]
@sebastianskejoe the email is still sent in the notification email to the repo owner
